baseurl = "https://journeyman33.github.io/k8s-resume-blog/"
title = "Cloud Kubernetes Resume Challenge"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "G-23SDG1K50P"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/k8s_resume_banner7.png"
  SEOTitle = "spec | journeyman Blog"
  description = "spec | two"
  keyword = "Microservice"
  slogan = "Forrest Brazeal + Kodekloud"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Not Found :"
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Charles Vosloo:  I am interested in Kubernetes, Devops, Opensource, family and outdoors."
  sidebar_avatar = "img/eye_of_africa_pic3.png" 

  featured_tags = false
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false
  # reward_guide = "" 

  friends = true
  bookmarks = true
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true
  email          = "voslooc@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/charlesvosloo/"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/journeyman33"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  gitlab         = "https://gitlab.com/-/user_settings/profile"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Civo Server > http://6276cc06-5948-4233-a3db-5cf822aa9f33.lb.civo.com/"
  href =  "http://6276cc06-5948-4233-a3db-5cf822aa9f33.lb.civo.com/"

  [[params.bookmark_link]]
  title =  "canva.com"
  href =  "https://canva.com"
  
  [[params.addtional_menus]]
  title =  "ARCHIVE"
  #href =  "/archive/"
  href = "https://journeyman33.github.io/k8s-resume-blog/archive/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  #href =  "/about/"
  href = "https://journeyman33.github.io/k8s-resume-blog/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"

  [params.giscus]
  data_repo="https://github.com/journeyman33/giscuss"
  data_repo_id=""
  data_category=""
  data_category_id="your category id"
  data_mapping="pathname"
  data_reactions_enabled="1"
  data_emit_metadata="0"
  data_theme="light"
  data_lang="en"
  crossorigin="anonymous"